name: Windows build

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2.0.0
        
    - name: Install Java 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
    
    - name: Install postgresql
      uses: ikalnytskyi/action-setup-postgres@v6
      with:
        username: postgres
        password: password
        database: testdb
        port: 5432
      id: postgres

    - name: Checkout opensource COBOL 4J
      uses: actions/checkout@v4
      with:
        repository: opensourcecobol/opensourcecobol4j
        path: opensourcecobol4j
    
    - name: Build libcobj.jar
      working-directory: opensourcecobol4j/libcobj
      run: |
        ./gradlew shadowJar
        mkdir C:\opensourcecobol4j\lib
        copy app/build/libs/libcobj.jar C:\opensourcecobol4j\lib

    - name: Restore NuGet packages of opensourcecobol4j
      run: nuget restore ./opensourcecobol4j/win/

    - name: Build ocesql.exe
      working-directory: opensourcecobol4j
      run: |
        msbuild /p:Configuration=Release /p:AdditionalIncludePaths=./:./cobj/:./win:./lib win/opensourcecobol4j.sln
        mkdir C:\opensourcecobol4j\bin
        mkdir C:\opensourcecobol4j\config
        copy win/x64/Release/cobj.exe C:\opensourcecobol4j\bin\
        copy config/*.conf C:\opensourcecobol4j\config\
        
    - name: Build ocesql4j.jar
      run: |
        cd dblibj
        copy ../opensourcecobol4j/libcobj/app/build/libs/libcobj.jar lib
        sbt assembly
    
    - name: Restore NuGet packages of ocesql4j
      run: nuget restore ./win/

    - name: Build ocesql.exe
      run: |
        msbuild /p:Configuration=Release /p:AdditionalIncludePaths=./:ocesql win/ocesql.sln
 
    - name: Place files of OCESQL 4j
      working-directory: win
      run: ./install.ps1

    - name: Test SQL connection
      working-directory: sample
      run: |
        $env:PATH+=";C:\opensourcecobol4j\bin;C:\ocesql4j\bin;C:\ocesql4j\config"
        $env:CLASSPATH="C:\opensourcecobol4j\lib\libcobj.jar;C:\ocesql4j\lib\ocesql4j.jar"
        copy ../copy/sqlca.cbl .
        ocesql FETCHTBL.cbl  FETCHTBL.cob
        ocesql INSERTTBL.cbl INSERTTBL.cob
        cobj INSERTTBL.cob
        cobj FETCHTBL.cob
        java INSERTTBL.java
        java FETCHTBL.java > sample-result

    - name: Compare result of test
      working-directory: sample
      run: |
        fc /b .\sample-result ..\win\sample-correct > test-result
        findstr "no differences encountered" test-result
      shell: cmd